Repository BrassMC/BrassLoader, pull requests merged in 2022-08, with the labels that each got.

#5 Adjust debug overlay to brass instead of vanilla
  build.gradle
  src/mixin/java/io/github/brassmc/brassloader/mixin/ClientBrandRetrieverMixin.java
  src/mixin/java/io/github/brassmc/brassloader/mixin/DebugScreenOverlayMixin.java
  src/mixin/java/io/github/brassmc/brassloader/mixin/MinecraftServerMixin.java
  src/mixin/resources/brassloader.mixins.json
Labels: enhancement, mixins

#6 Add mods button to pause screen
  src/mixin/java/io/github/brassmc/brassloader/mixin/PauseScreenMixin.java
  src/mixin/resources/brassloader.mixins.json
Labels: enhancement

#7 Implement mod discovery
  build.gradle
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/InvalidEntrypointException.java
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/InvalidModidException.java
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/MetadataParseException.java
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/MetadataUtils.java
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/ModDiscovery.java
  src/boot/java/io/github/brassmc/brassloader/boot/mods/ModContainer.java
  src/boot/java/io/github/brassmc/brassloader/boot/util/Constants.java
  src/mixin/java/io/github/brassmc/brassloader/mixin/BootstrapMixin.java
  src/mixin/resources/brassloader.mixins.json
Labels: enhancement, triage

#8 Fix NoSuchFileException thrown when mods folder was not created.
  src/boot/java/io/github/brassmc/brassloader/boot/discovery/ModDiscovery.java
Labels: bug

#9 Introduce custom mod panel system.
  src/main/java/io/github/brassmc/brassloader/gui/InformationPanel.java
  src/main/java/io/github/brassmc/brassloader/gui/ModsListScreen.java
Labels: enhancement

#12 Change Window Title
  src/mixin/java/io/github/brassmc/brassloader/mixin/MinecraftMixin.java
Labels: enhancement, mixins
